In [1]:
import pandas as pd

In [2]:
# load dataset

df = pd.read_csv('/content/Final.csv')

In [3]:
df.head()

,user_id,age,age_group,gender,country,occupation,education_level,income_bracket,relationship_status,primary_platform,...,is_verified_account,is_content_creator,uses_ai_features,daily_notifications,checks_phone_first_morning,uses_screen_time_limits,monthly_active_users_billions,avg_daily_time_minutes,avg_engagement_rate_pct,year_over_year_growth_pct
0,USR-000001,22,18-24,Non-Binary,Philippines,Teacher/Educator,Doctoral/Professional,$100K-$150K,Married,Facebook,...,0,0,0,20,1,0,3.07,33,1.5,2.5
1,USR-000002,31,25-34,Prefer Not to Say,United Kingdom,Marketing Professional,High School or Below,$50K-$75K,In a Relationship,TikTok,...,0,0,0,31,1,0,1.99,58,2.8,17.0
2,USR-000003,21,18-24,Female,UAE,Legal Professional,High School or Below,$25K-$50K,Single,Instagram,...,0,0,0,47,1,0,3.00,35,2.2,13.0
3,USR-000004,33,25-34,Female,Saudi Arabia,Unemployed,Some College,$25K-$50K,Single,Instagram,...,0,0,0,28,1,0,3.00,35,2.2,13.0
4,USR-000005,23,18-24,Female,Poland,Sales Professional,Vocational/Trade,$25K-$50K,It's Complicated,Reddit,...,0,1,0,149,1,0,0.77,24,2.5,15.0

In [6]:
import pandas as pd

# Display dataset shapes and columns.

df.shape
df.columns

Index(['user_id', 'age', 'age_group', 'gender', 'country', 'occupation',
       'education_level', 'income_bracket', 'relationship_status',
       'primary_platform', 'num_platforms_used', 'daily_screen_time_minutes',
       'weekly_sessions', 'avg_session_duration_minutes',
       'preferred_content_type', 'primary_device', 'usage_purpose',
       'posts_per_week', 'likes_per_day', 'comments_per_day',
       'shares_per_week', 'followers_count', 'following_count',
       'engagement_rate_pct', 'video_consumption_daily_minutes',
       'has_purchased_via_social', 'follows_influencers', 'ad_click_frequency',
       'monthly_social_spending_usd', 'uses_privacy_settings',
       'experienced_cyberbullying', 'reports_fake_news_frequency',
       'self_reported_mental_health_effect', 'sleep_hours_per_night',
       'addiction_level_1_to_10', 'productivity_impact',
       'platform_satisfaction', 'account_created_date', 'account_age_years',
       'is_verified_account', 'is_content_creator', 'uses_ai_features',
       'daily_notifications', 'checks_phone_first_morning',
       'uses_screen_time_limits', 'monthly_active_users_billions',
       'avg_daily_time_minutes', 'avg_engagement_rate_pct',
       'year_over_year_growth_pct'],
      dtype='object')

In [7]:
# check for missing values.
df.isnull().sum()

user_id                               0
age                                   0
age_group                             0
gender                                0
country                               0
occupation                            0
education_level                       0
income_bracket                        0
relationship_status                   0
primary_platform                      0
num_platforms_used                    0
daily_screen_time_minutes             0
weekly_sessions                       0
avg_session_duration_minutes          0
preferred_content_type                0
primary_device                        0
usage_purpose                         0
posts_per_week                        0
likes_per_day                         0
comments_per_day                      0
shares_per_week                       0
followers_count                       0
following_count                       0
engagement_rate_pct                   0
video_consumption_daily_minutes       0
has_purchased_via_social              0
follows_influencers                   0
ad_click_frequency                    0
monthly_social_spending_usd           0
uses_privacy_settings                 0
experienced_cyberbullying             0
reports_fake_news_frequency           0
self_reported_mental_health_effect    0
sleep_hours_per_night                 0
addiction_level_1_to_10               0
productivity_impact                   0
platform_satisfaction                 0
account_created_date                  0
account_age_years                     0
is_verified_account                   0
is_content_creator                    0
uses_ai_features                      0
daily_notifications                   0
checks_phone_first_morning            0
uses_screen_time_limits               0
monthly_active_users_billions         0
avg_daily_time_minutes                0
avg_engagement_rate_pct               0
year_over_year_growth_pct             0
dtype: int64

In [12]:
# User demographics
print(df['gender'].value_counts())
print(df['age_group'].value_counts())
print(df['country'].value_counts())

gender
Female               11930
Male                 11574
Non-Binary            1009
Prefer Not to Say      487
Name: count, dtype: int64
age_group
25-34    7091
18-24    5474
35-44    4498
45-54    2947
13-17    2076
55-64    1959
65+       955
Name: count, dtype: int64
country
India             3598
United States     3175
Brazil            2139
Indonesia         1646
Pakistan          1087
Nigeria           1084
Mexico             834
United Kingdom     821
Japan              811
Philippines        795
Germany            776
France             578
South Korea        570
Thailand           568
Saudi Arabia       539
Canada             531
Egypt              517
Turkey             500
Australia          414
Vietnam            413
Bangladesh         401
South Africa       397
Malaysia           295
Argentina          279
Netherlands        271
Spain              262
Poland             259
Italy              253
Colombia           251
Kenya              245
Chile              152
Sweden             147
Singapore          138
Morocco            129
UAE                125
Name: count, dtype: int64

In [13]:
# screen time analysis

print(df["daily_screen_time_minutes"].describe())
print(df.groupby("age_group")["daily_screen_time_minutes"].mean().sort_values(ascending=False))

count    25000.000000
mean       141.122480
std         62.577221
min          5.000000
25%         95.000000
50%        137.000000
75%        182.000000
max        467.000000
Name: daily_screen_time_minutes, dtype: float64
age_group
13-17    197.089114
18-24    176.159116
25-34    148.991115
35-44    130.016007
45-54    104.093655
55-64     79.064319
65+       54.084817
Name: daily_screen_time_minutes, dtype: float64

In [14]:
# platform popularity

print(df["primary_platform"].value_counts())

primary_platform
Instagram      4434
Facebook       3939
YouTube        3759
TikTok         3594
X (Twitter)    1544
Snapchat       1267
LinkedIn       1209
Pinterest      1021
Reddit         1016
WhatsApp        791
Telegram        718
Threads         534
Bluesky         478
RedNote         466
Discord         230
Name: count, dtype: int64

In [15]:
# content preference
print(df["preferred_content_type"].value_counts())
print(df.groupby("primary_device")["preferred_content_type"].value_counts())

preferred_content_type
Short-Form Video    5575
Image/Photo         3752
Story/Reel          3603
Text Post           2489
Long-Form Video     2434
Carousel            1737
Meme                1239
Live Stream         1228
Poll/Quiz           1004
Podcast/Audio        741
Article/Blog         727
Infographic          471
Name: count, dtype: int64
primary_device  preferred_content_type
Desktop         Short-Form Video           934
                Image/Photo                679
                Story/Reel                 630
                Long-Form Video            476
                Text Post                  443
                Carousel                   314
                Live Stream                227
                Meme                       212
                Poll/Quiz                  194
                Article/Blog               129
                Podcast/Audio              114
                Infographic                 69
Smart TV        Short-Form Video           424
                Image/Photo                278
                Story/Reel                 240
                Text Post                  179
                Long-Form Video            159
                Carousel                   116
                Meme                       107
                Live Stream                 80
                Poll/Quiz                   66
                Article/Blog                51
                Podcast/Audio               48
                Infographic                 41
Smartphone      Short-Form Video          3520
                Image/Photo               2317
                Story/Reel                2232
                Text Post                 1553
                Long-Form Video           1510
                Carousel                  1078
                Live Stream                773
                Meme                       767
                Poll/Quiz                  607
                Podcast/Audio              470
                Article/Blog               445
                Infographic                301
Tablet          Short-Form Video           537
                Story/Reel                 391
                Image/Photo                362
                Text Post                  255
                Long-Form Video            236
                Carousel                   184
                Meme                       122
                Live Stream                119
                Poll/Quiz                  104
                Article/Blog                84
                Podcast/Audio               75
                Infographic                 41
Wearable        Short-Form Video           160
                Image/Photo                116
                Story/Reel                 110
                Text Post                   59
                Long-Form Video             53
                Carousel                    45
                Podcast/Audio               34
                Poll/Quiz                   33
                Meme                        31
                Live Stream                 29
                Infographic                 19
                Article/Blog                18
Name: count, dtype: int64

In [16]:
# Followers distribution
print(df[["user_id","followers_count"]].sort_values("followers_count", ascending=False).head(10))
print(df["followers_count"].describe())

          user_id  followers_count
24029  USR-024030           525545
22997  USR-022998           381210
22283  USR-022284           270298
24373  USR-024374           270007
18653  USR-018654           253622
23796  USR-023797           245349
72     USR-000073           242916
8544   USR-008545           230505
20545  USR-020546           230019
11286  USR-011287           220205
count     25000.000000
mean       1700.168840
std        8671.294106
min           0.000000
25%          64.000000
50%         244.000000
75%         942.000000
max      525545.000000
Name: followers_count, dtype: float64

In [17]:
# Engagement analysis

print(df.groupby("primary_platform")["engagement_rate_pct"].mean().sort_values(ascending=False))
print(df.groupby("is_content_creator")["engagement_rate_pct"].mean())

primary_platform
TikTok         2.795426
Reddit         2.468691
RedNote        2.322103
Instagram      2.200120
LinkedIn       1.952903
YouTube        1.910857
Threads        1.864831
Snapchat       1.792281
Bluesky        1.710502
Pinterest      1.584760
Facebook       1.501691
X (Twitter)    1.417487
Discord        0.000000
Telegram       0.000000
WhatsApp       0.000000
Name: engagement_rate_pct, dtype: float64
is_content_creator
0    1.864484
1    1.898848
Name: engagement_rate_pct, dtype: float64

In [18]:
# social commerce

print(df["has_purchased_via_social"].value_counts(normalize=True) * 100)
print(df.groupby("income_bracket")["monthly_social_spending_usd"].mean().sort_values(ascending=False))

has_purchased_via_social
0    61.552
1    38.448
Name: proportion, dtype: float64
income_bracket
$75K-$100K     12.239499
$50K-$75K      12.057189
$25K-$50K      11.957670
$100K-$150K    11.865532
$150K+         11.768932
< $10K         11.700735
$10K-$25K      11.674902
Name: monthly_social_spending_usd, dtype: float64

In [19]:
# churn risk analysis
df["churn_risk"] = ((df["daily_screen_time_minutes"] < 30) &
                    (df["monthly_social_spending_usd"] == 0))
print("Churn risk users:", df["churn_risk"].sum())
print(df[df["churn_risk"] == True]["age_group"].value_counts())

Churn risk users: 0
Series([], Name: count, dtype: int64)

In [20]:
# influence impact
print(df.groupby("follows_influencers")[["monthly_social_spending_usd","engagement_rate_pct"]].mean())
print(df.groupby("follows_influencers")["platform_satisfaction"].value_counts(normalize=True))

                     monthly_social_spending_usd  engagement_rate_pct
follows_influencers
0                                      11.883353             1.868281
1                                      11.887606             1.870449
follows_influencers  platform_satisfaction
0                    Satisfied                0.303296
                     Neutral                  0.280018
                     Dissatisfied             0.203618
                     Very Satisfied           0.114773
                     Very Dissatisfied        0.098295
1                    Satisfied                0.298432
                     Neutral                  0.277233
                     Dissatisfied             0.198137
                     Very Satisfied           0.123514
                     Very Dissatisfied        0.102683
Name: proportion, dtype: float64

In [21]:
# cyber bulling
print(df["experienced_cyberbullying"].value_counts())
print(df.groupby("gender")["experienced_cyberbullying"].mean() * 100)
print(df.groupby("age_group")["experienced_cyberbullying"].mean() * 100)

experienced_cyberbullying
0    20447
1     4553
Name: count, dtype: int64
gender
Female               18.013412
Male                 18.541559
Non-Binary           17.740337
Prefer Not to Say    16.221766
Name: experienced_cyberbullying, dtype: float64
age_group
13-17    17.533719
18-24    17.939350
25-34    18.333098
35-44    18.941752
45-54    18.052257
55-64    18.478816
65+      16.858639
Name: experienced_cyberbullying, dtype: float64

In [22]:
# mental health impact
print(df["self_reported_mental_health_effect"].value_counts())
print(df.groupby("addiction_level_1_to_10")["sleep_hours_per_night"].mean())

self_reported_mental_health_effect
Neutral            12262
Mostly Negative     7403
Mostly Positive     4184
Negative             898
Positive             253
Name: count, dtype: int64
addiction_level_1_to_10
1     7.435288
2     7.165665
3     7.005420
4     6.801590
5     6.612991
6     6.401352
7     6.186462
8     5.944382
9     5.687097
10    4.933333
Name: sleep_hours_per_night, dtype: float64

In [23]:
df.to_csv('finaldataset.csv',index=False)

In [24]:
from google.colab import files
files.download("finaldataset.csv")